# -*- coding: utf-8 -*-
import sys
# Form implementation generated from reading ui file 'Form_Input.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Form_ShowData import Ui_Form_ShowData

class Ui_Form_Input(object):
    tempList = []
    programmingLanguageList = []
    list2d = []
    index = 0

    def setupUi(self, Form_Input):

        # Windows heading
        Form_Input.setObjectName("Form_Input")
        Form_Input.resize(1000, 600)

        # Widget Object
        self.centralwidget = QtWidgets.QWidget(Form_Input)
        self.centralwidget.setObjectName("centralwidget")

        # Label
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(70, 16, 87, 30))
        self.label_1.setObjectName("label_1")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 66, 87, 30))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 116, 87, 30))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 16, 87, 30))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 200, 87, 30))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 80, 87, 30))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 170, 87, 30))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 254, 87, 30))
        self.label_8.setObjectName("label_8")

        # Line Edit | Input Line
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(160, 10, 250, 40))
        self.lineEdit_1.setObjectName("lineEdit_1")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 250, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(550, 10, 250, 40))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(550, 160, 250, 40))
        self.lineEdit_4.setObjectName("lineEdit_4")

        # Combo Box
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(160, 110, 180, 42))
        self.comboBox_1.setObjectName("comboBox_1")

        # Button
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(250, 320, 200, 50))
        self.pushButton_1.setObjectName("pushButton_1")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 320, 200, 50))
        self.pushButton_2.setObjectName("pushButton_2")

        # Button Event Goes Here
        # noinspection PyUnresolvedReferences
        self.pushButton_1.clicked.connect(self.onClickButtonOk)
        # noinspection PyUnresolvedReferences
        self.pushButton_2.clicked.connect(self.onClickButtonClear)

        # Group Boxes
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(550, 220, 450, 90))
        self.groupBox_1.setObjectName("groupBox")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 170, 250, 91))
        self.groupBox_2.setObjectName("groupBox_1")

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(550, 60, 300, 90))
        self.groupBox_3.setObjectName("groupBox_2")

        # Radio Button
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_1.setGeometry(QtCore.QRect(10, 30, 110, 34))
        self.radioButton_1.setObjectName("radioButton_1")

        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 30, 110, 34))
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 30, 100, 34))
        self.radioButton_3.setObjectName("radioButton_3")

        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(100, 30, 100, 34))
        self.radioButton_4.setObjectName("radioButton_4")

        # Check Box
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_1)
        self.checkBox_1.setGeometry(QtCore.QRect(10, 30, 70, 34))
        self.checkBox_1.setObjectName("checkBox_1")

        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_1)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 30, 70, 34))
        self.checkBox_2.setObjectName("checkBox_2")

        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_1)
        self.checkBox_3.setGeometry(QtCore.QRect(180, 30, 70, 34))
        self.checkBox_3.setObjectName("checkBox_3")


        Form_Input.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Form_Input)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")

        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")

        self.menuview = QtWidgets.QMenu(self.menubar)
        self.menuview.setObjectName("menuview")
        Form_Input.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Form_Input)
        self.statusbar.setObjectName("statusbar")
        Form_Input.setStatusBar(self.statusbar)

        # Menu View DropDown
        self.formInputData = QtWidgets.QAction(Form_Input)
        self.formInputData.setObjectName("Form input Data")

        self.formShowdata = QtWidgets.QAction(Form_Input)
        self.formShowdata.setObjectName("actionUpdate_Data")

        # Menu View DropDown Event
        # noinspection PyUnresolvedReferences
        self.formShowdata.triggered.connect(self.showMenuViewForm)

        self.menuview.addAction(self.formInputData)
        self.menuview.addAction(self.formShowdata)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuview.menuAction())

        self.retranslateUi(Form_Input)
        QtCore.QMetaObject.connectSlotsByName(Form_Input)

    def retranslateUi(self, Form_Input):
        _translate = QtCore.QCoreApplication.translate
        Form_Input.setWindowTitle(_translate("Form_Input", "MainWindow"))
        self.label_1.setText(_translate("Form_Input", "NAME"))
        self.label_2.setText(_translate("Form_Input", "NPM"))
        self.label_3.setText(_translate("Form_Input", "CLASS"))
        self.label_4.setText(_translate("Form_Input", "ADDRESS"))
        self.label_5.setText(_translate("Form_Input", "GENDER"))
        self.label_6.setText(_translate("Form_Input", "STATUS"))
        self.label_7.setText(_translate("Form_Input", "HOBBY"))
        self.label_8.setText(_translate("Form_Input", "LANGUAGE"))

        self.pushButton_1.setText(_translate("Form_Input", "OK"))
        self.pushButton_2.setText(_translate("Form_Input", "CLEAR"))

        self.groupBox_1.setTitle(_translate("Form_Input", "Programming Language You Mastered or Familiar With"))
        self.groupBox_2.setTitle(_translate("Form_Input", "Your Gender"))
        self.groupBox_3.setTitle(_translate("Form_Input", "User Status"))

        self.radioButton_1.setText(_translate("Form_Input", "Laki - Laki"))
        self.radioButton_2.setText(_translate("Form_Input", "Perempuan"))
        self.radioButton_1.setChecked(True)

        self.radioButton_3.setText(_translate("Form_Input", "Active"))
        self.radioButton_4.setText(_translate("Form_Input", "Inactive"))
        self.radioButton_3.setChecked(True)

        self.checkBox_1.setText(_translate("Form_Input", "C#"))
        self.checkBox_2.setText(_translate("Form_Input", "Python"))
        self.checkBox_3.setText(_translate("Form_Input", "Lua"))

        self.comboBox_1.addItems(("5A", "5B", "5C", "5D", "5E", "5F", "5G",
                                  "5H", "5I", "5J", "5K", "5L", "5M", "5N", "O"))

        self.menufile.setTitle(_translate("Form_Input", "file"))
        self.menuview.setTitle(_translate("Form_Input", "view"))
        self.formInputData.setText(_translate("Form_Input", "Update Data"))
        self.formShowdata.setText(_translate("Form_Input", "Show data"))

    # def onClickButtonOk(self):

    def onClickButtonOk(self):

        if(self.lineEdit_1.text() != "" and self.lineEdit_2.text() != ""
        and self.lineEdit_3.text() != "" and self.lineEdit_4.text() != ""):
            self.tempList.append(self.index + 1)
            self.tempList.append(self.lineEdit_1.text())
            self.tempList.append(self.lineEdit_2.text())

            self.tempList.append(self.comboBox_1.itemText(int(self.comboBox_1.currentIndex())))

            if (self.radioButton_1.isChecked()):
                self.tempList.append(self.radioButton_1.text())

            else:
                self.tempList.append(self.radioButton_2.text())

            self.tempList.append(self.lineEdit_3.text())

            self.tempList.append(self.lineEdit_4.text())

            if (self.radioButton_1.isChecked()):
                self.tempList.append(self.radioButton_3.text())

            else:
                self.tempList.append(self.radioButton_4.text())

            if (self.checkBox_1.isChecked() == True):
                self.programmingLanguageList.append(self.checkBox_1.text())

            if (self.checkBox_2.isChecked() == True):
                self.programmingLanguageList.append(self.checkBox_2.text())

            if (self.checkBox_2.isChecked() == True):
                self.programmingLanguageList.append(self.checkBox_3.text())

            if (self.checkBox_1.isChecked() != True and self.checkBox_2.isChecked() != True and
                    self.checkBox_2.isChecked() != True):
                self.tempList.append("None")
            else:
                # appending ProgrammingLanguageList into tempList
                self.tempList.append(self.programmingLanguageList)
                self.index += 1

                # adding data to Variable type list list2d
                self.list2d.append(self.tempList)
                print(self.list2d)
                self.tempList.clear()
                self.onClickButtonClear()

                # adding data to Form ShowData List2d


        else:
            print("input filed cannot be empty")



    def onClickButtonClear(self):
        self.lineEdit_1.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.lineEdit_4.setText("")

        self.radioButton_1.click()
        self.radioButton_3.click()

        self.comboBox_1.setCurrentIndex(0)

        self.checkBox_1.setChecked(False)
        self.checkBox_2.setChecked(False)
        self.checkBox_3.setChecked(False)

    def showMenuViewForm(self):
        self.showDataWindow = QtWidgets.QMainWindow()
        self.showDataUi = Ui_Form_ShowData()
        self.showDataUi.setupUi(self.showDataWindow)
        self.showDataWindow.show()
