# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UAS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.label5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label5.setObjectName("label5")
        self.verticalLayout.addWidget(self.label5)
        self.label4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label4.setObjectName("label4")
        self.verticalLayout.addWidget(self.label4)
        self.label3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label3.setObjectName("label3")
        self.verticalLayout.addWidget(self.label3)
        self.label6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label6.setObjectName("label6")
        self.verticalLayout.addWidget(self.label6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 19, 251, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit1.setObjectName("lineEdit1")
        self.verticalLayout_2.addWidget(self.lineEdit1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout_2.addWidget(self.lineEdit2)
        self.lineEdit3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit3.setObjectName("lineEdit3")
        self.verticalLayout_2.addWidget(self.lineEdit3)
        self.lineEdit4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit4.setObjectName("lineEdit4")
        self.verticalLayout_2.addWidget(self.lineEdit4)
        self.lineEdit5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit5.setObjectName("lineEdit5")
        self.verticalLayout_2.addWidget(self.lineEdit5)

        self.lineEdit6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit6.setObjectName("lineEdit6")
        self.verticalLayout_2.addWidget(self.lineEdit6)

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 170, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonInsert.setObjectName("ButtonInsert")
        self.horizontalLayout.addWidget(self.ButtonInsert)
        self.ButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonUpdate.setObjectName("ButtonUpdate")
        self.horizontalLayout.addWidget(self.ButtonUpdate)
        self.ButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonDelete.setObjectName("ButtonDelete")
        self.horizontalLayout.addWidget(self.ButtonDelete)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 220, 471, 261))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Event
        self.ButtonInsert.clicked.connect(self.insertpenjualan)
        self.ButtonUpdate.clicked.connect(self.updatepenjualan)
        self.ButtonDelete.clicked.connect(self.deletepenjualan)


    def insertpenjualan(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                port=3307,
                database="db_penjualan_uas_"
            )

            cursor = mydb.cursor()
            id = self.lineEdit1.text()
            barkode = self.lineEdit2.text()
            nama = self.lineEdit3.text()
            kategori = self.lineEdit4.text()
            qty = self.lineEdit5.text()
            harga = self.lineEdit6.text()
            sql = "INSERT INTO product (id, barkode, nama, kategori, qty, harga) VALUES (%s,%s,%s,%s,%s,%s)"
            val = (id, barkode, nama, kategori, qty, harga)
            cursor.execute(sql, val)
            mydb.commit()
            self.loadpenjualan()
            self.label1.setText("Data penjualan Berhasil Disimpan")

            self.lineEdit1.setText("")
            self.lineEdit2.setText("")
            self.lineEdit3.setText("")
            self.lineEdit4.setText("")
            self.lineEdit5.setText("")
            self.lineEdit6.setText("")
        except mc.Error as e:
            self.label1.setText("Data penjualan Gagal Disimpan")

    def updatepenjualan(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                port=3307,
                database="db_penjualan_uas_"
            )

            cursor = mydb.cursor()
            npm = self.lineEdit1.text()
            namamhs = self.lineEdit2.text()
            kelasmhs = self.lineEdit3.text()
            jurusanmhs = self.lineEdit4.text()
            tanggal_lahirmhs = self.lineEdit5.text()

            sql = "UPDATE product set barkode = %s, nama = %s, kategori = %s, qty = %s, harga = %s where id = %s"
            val = (namamhs, kelasmhs, jurusanmhs, tanggal_lahirmhs, npm)
            cursor.execute(sql, val)
            mydb.commit()
            self.label6.setText("Data penjualan Berhasil DiUpdate")
            self.loadpenjualan()


            self.lineEdit1.setText("")
            self.lineEdit2.setText("")
            self.lineEdit3.setText("")
            self.lineEdit4.setText("")
            self.lineEdit5.setText("")
            self.lineEdit6.setText("")

        except mc.Error as e:
            self.label1.setText("Data penjualan Gagal DiUpdate")

    def deletepenjualan(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                port=3307,
                database="db_penjualan_uas_"
            )

            cursor = mydb.cursor()
            npm = self.lineEdit1.text()

            sql = "DELETE FROM product where id = %s"
            val = (npm,)
            cursor.execute(sql, val)
            mydb.commit()

            self.label1.setText("Data penjualan Berhasil Dihapus")
            self.loadpenjualan()

            self.lineEdit1.setText("")
        except mc.Error as e:
            self.label1.setText("Data penjualan Gagal DiHapus")

    def loadpenjualan(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                port="3307",
                database="db_penjualan_uas_"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM product")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.label1.setText("berhasil")

        except mc.Error as err:
            self.label1.setText("gagal")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "ID"))
        self.label2.setText(_translate("MainWindow", "BARKODE"))
        self.label5.setText(_translate("MainWindow", "NAMA"))
        self.label4.setText(_translate("MainWindow", "KATEGORI"))
        self.label3.setText(_translate("MainWindow", "QUANTITY"))
        self.label6.setText(_translate("MainWindow", "HARGA"))
        self.ButtonInsert.setText(_translate("MainWindow", "Insert"))
        self.ButtonUpdate.setText(_translate("MainWindow", "Update"))
        self.ButtonDelete.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BARKODE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "KATEGORI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "QTY"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "HARGA"))

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        self.setupUi(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    w.loadpenjualan()
    sys.exit(app.exec_())