# Simple input program

# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'part1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 220, 50, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(120, 120, 80, 30))
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(170, 40, 113, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 35, 20))
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(110, 40, 50, 20))
        self.label_1.setObjectName("label_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 200, 50, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 120, 70, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 210, 50, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # noinspection PyUnresolvedReferences
        self.pushButton_1.clicked.connect(self.onClickedButton1)
        # noinspection PyUnresolvedReferences
        self.pushButton_2.clicked.connect(self.onClickedButton2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "output 2"))
        self.pushButton_1.setText(_translate("MainWindow", "OK"))
        self.label_2.setText(_translate("MainWindow", "NPM"))
        self.label_1.setText(_translate("MainWindow", "NAMA"))
        self.label_3.setText(_translate("MainWindow", "output 1"))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


    def onClickedButton1(self):


        try:
            int(self.lineEdit_1.text())
            int(self.lineEdit_2.text())
        except ValueError or self.lineEdit_1.text() == ("True" or "False") or self.lineEdit_2.text() == ("True" or "False"):
            self.label.setGeometry(QtCore.QRect(280, 210, 80, 20))

            self.label.setText("Value Error")
            if(self.lineEdit_1.text() == ""):
                print(self.label.setText("value cannot be empty"))
                self.label.setGeometry(QtCore.QRect(280, 210, 200, 20))

        else:
            self.label_3.setText(self.lineEdit_1.text())
            self.label_4.setText(self.lineEdit_2.text())

            self.label.setText(str(int(self.lineEdit_1.text()) + int(self.lineEdit_2.text())))

            self.label.setGeometry(QtCore.QRect(280, 210, 50, 20))
            self.lineEdit_1.setText("")
            self.lineEdit_2.setText("")

    def onClickedButton2(self):
        self.lineEdit_1.setText("")
        self.lineEdit_2.setText("")


app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(window)
window.show()
sys.exit(app.exec_())
